# Generated by Django 5.0 on 2024-02-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_jobs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs',
            table='jobs',
        ),
    ]
