# Generated by Django 5.0 on 2024-02-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_alter_jobs_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='JOBID'),
        ),
    ]
